version: '3'
services:
  mysql-server:
    image: 'mysql'
    container_name: quarkus-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: quarkus_playground
      MYSQL_USER: quarkfly
      MYSQL_PASSWORD: quarkfly
    ports:
      - 3306:3306
    restart: unless-stopped
  quarkus-app:
    depends_on:
      - mysql-server
    build:
      context: ./../../..
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: quarkus-app
    ports: 
      - 8080:8080